import { sidebar } from "vuepress-theme-hope";

export const zhSidebar = sidebar({
	"/": [
		"",
		{
			icon: "html",
			text: "Html",
			prefix: "html/",
			link: "html/",
			children: [
				"README.md",
				"h1-h6.md",
				"p.md",
				"text.md",
				"box.md",
				"image.md",
				"table.md",
				"list.md",
			],
		},
		{
			icon: "css",
			text: "Css",
			prefix: "css/",
			link: "css/",
			children: [
				"README.md",
				"text.md",
				"a.md",
				"background.md",
				"unit.md",
				"block.md",
				"flex.md",
				"grid.md",
				"animation.md",
				"media.md",
			],
		},
		{
			icon: "javascript",
			text: "JavaCcript",
			prefix: "js/",
			link: "js/",
			children: [
				"README.md",
				"watermark.md",
				"iterator.md",
				"parseInt-map.md",
				"typeof.md",
			],
		},
		{
			icon: "vue",
			text: "Vue",
			prefix: "vue/",
			link: "vue/",
			children: [
				"README.md",
				"autoUpdate.md",
				"vue-performance.md",
				"Vue3-script-setup.md",
			],
		},
		{
			icon: "nodeJS",
			text: "Node",
			prefix: "node/",
			link: "node/",
			children: ["README.md", "nest.md", "pm2.md"],
		},
		{
			icon: "debug",
			text: "Bug与优化",
			prefix: "bug/",
			link: "bug/",
			children: [
				"README.md",
				"hooksLoading.md",
				"installOrder.md",
				"search.md",
				"homeGridView.md",
				"performance.md",
			],
		},
		{
			icon: "git",
			text: "git",
			prefix: "git/",
			link: "git/",
			children: ["README.md"],
		},
		{
			icon: "projice",
			text: "项目工程",
			prefix: "projice/",
			link: "projice/",
			children: ["README.md"],
		},
		{
			icon: "demos",
			text: "demos",
			prefix: "demos/",
			link: "demos/",
			children: ["README.md"],
		},
		
		// "slides",
	],
});
